alias -- cat=bat
alias -- dc='docker compose'
alias -- dcc='docker compose cp'
alias -- dcd='docker compose down'
alias -- dce='docker compose exec'
alias -- dci='docker compose inspect'
alias -- dcl='docker compose logs'
alias -- dclf='docker compose logs -f'
alias -- dcr='docker compose restart'
alias -- dcu='docker compose up'
alias -- eza='eza --icons --git'
alias -- g=git
alias -- k=kubectl
alias -- kj='kubectl -o json'
alias -- kw='kubectl -o wide'
alias -- ky='kubectl -o yaml'
alias -- la='eza -a'
alias -- lg=lazygit
alias -- ll='eza -l'
alias -- lla='eza -la'
alias -- ls=eza
alias -- lt='eza --tree'
alias -- nb='nix build --json --no-link --print-build-logs'
alias -- ops='op run --no-masking'
alias -- s='doppler run'
alias -- tf=terraform
alias -- vi=nvim
alias -- vim=nvim
alias -- watch=viddy
alias -- wt='git worktree'
